# standard jekyll configuration

permalink: date
pygments: true
exclude: ['Rakefile', 'README.markdown', 'config.rb', 'TODO.markdown', 'Gemfile', 'Gemfile.lock']
markdown: rdiscount

# configuration required for some pages

domain: grist.brownsofa.org
title: Grist Blog
byline: on beer and home brewing
author: Ian
email: ian.truslove@gmail.com

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

google_analytics:
  account: UA-27679933-1

# github:
#   username: ghusername

disqus:
   id: grist-blog
